import React, { useState } from "react";
import { Button } from "../../lib";
import Header from "../Header";
import { Keyboard } from "@bigbinary/neeto-icons";

const Buttons = () => {
  const [loading, setLoading] = useState(false);
  const toggle = () => {
    setLoading(!loading);
  };
  return (
    <div className="w-full">
      <Header title="Buttons" />
      <div className="p-6 space-y-6">
        <Button onClick={toggle} label="Toggle loadingstate" />
        <div className="grid grid-cols-2 gap-6">
          <div className="p-4 space-y-8 border border-indigo-500 border-dashed">
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                disabled
              />
              <Button
                iconPosition="left"
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                icon={Keyboard}
                iconPosition="left"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                disabled
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                loading
                icon={Keyboard}
                iconPosition="right"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                disabled
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                label="Label"
                loading
                icon={Keyboard}
              />
            </div>
          </div>
          <div className="p-4 space-y-8 border border-indigo-500 border-dashed">
            <div className="space-x-8">
              <Button loading={loading} onClick={toggle} label="Label" />
              <Button loading={loading} onClick={toggle} label="Label" />
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                disabled
              />
              <Button loading={loading} onClick={toggle} label="Label" />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                disabled
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                loading
                icon={Keyboard}
                iconPosition="right"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                disabled
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                label="Label"
                loading
                icon={Keyboard}
              />
            </div>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-6">
          <div className="p-4 space-y-8 border border-indigo-500 border-dashed">
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                disabled
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                loading
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                disabled
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                loading
                icon={Keyboard}
                iconPosition="right"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                disabled
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="secondary"
                label="Label"
                loading
                icon={Keyboard}
              />
            </div>
          </div>
          <div className="p-4 space-y-8 border border-indigo-500 border-dashed">
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                disabled
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                loading
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                disabled
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                loading
                icon={Keyboard}
                iconPosition="right"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                disabled
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="secondary"
                label="Label"
                loading
                icon={Keyboard}
              />
            </div>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-6">
          <div className="p-4 space-y-8 border border-indigo-500 border-dashed">
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                disabled
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                loading
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                disabled
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                loading
                icon={Keyboard}
                iconPosition="right"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                disabled
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                size="large"
                style="danger"
                label="Label"
                loading
                icon={Keyboard}
              />
            </div>
          </div>
          <div className="p-4 space-y-8 border border-indigo-500 border-dashed">
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                disabled
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                disabled
                icon={Keyboard}
                iconPosition="right"
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                loading
                icon={Keyboard}
                iconPosition="right"
              />
            </div>
            <div className="space-x-8">
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                disabled
                icon={Keyboard}
              />
              <Button
                loading={loading}
                onClick={toggle}
                style="danger"
                label="Label"
                loading
                icon={Keyboard}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Buttons;
